# TODO replace name with name of ebook: 101: Intro to Web, 411: Front-Ends with React...etc
site_name: JS411 ebook

# TODO inside `ebook-folder/`
# TODO run `git clone https://github.com/squidfunk/mkdocs-material.git`
# TODO run `pip install -r requirements.txt` (see inside mkdocs-material/)
# TODO run `mkdocs build` to build the static files into "/site"
# TODO run `mkdocs serve` to serve those files to http://127.0.0.1:8000
# TODO replace all CAPITALIZED words with appropriate titles
# ! Use the files in workspace/resources to quickly generate class and lesson templates, see `cp ...` script at bottom of each file
# ! Use the folder workspace/developmentDocumentation to record thoughts and future improvements

# defines where the markdown to build from
# docs_dir: 'test-node-book'

# defines where to put the generated static files
# site_dir: 'docs'

# "pages" has been deprecated
# use this to create the nav bar on the left-side of the window view
# TODO replace all CAPITALIZED words with appropriate titles

nav:
    - Home: 'index.md'
    - 'Module One: Intro to React':
      - 'Pre-Class 1 Lessons': 
        - Prepare Your Machine: preCourse/setupInstructions.md
        - Succeed in this Course: preCourse/succeedInThisCourse.md
        - Submitting Homework: preCourse/submittingHomework.md
        - Intro to React: module-1/introToReact.md
        - CRA Overview: module-1/CRA-overview.md
        - React DevTools: module-1/reactDeveloperTools-pt1.md
        - Bonus - HTML + JSX: module-1/bonusLesson.md
        - Class 1 ToDo App: module-1/class-1.md
      - 'Pre-Class 2 Lessons':
        - State & Props Intro: module-1/introToStateAndProps.md
        - Fetch, Store, Render: module-1/fetchStoreRender.md
        - Class 2 Beer App: module-1/class-2.md
      - 'Pre-Class 3 Lessons':
        - Conditional Rendering: module-1/conditionalRendering.md
        - Dynamic Rendering: module-1/dynamicRendering.md
        - Class 3 Address Book: module-1/class-3.md
      - 'Pre-Class 4 Lessons':
        - Forms in React: module-1/formsInReact.md
        - Hackathon Overview: module-1/hackathonOverview.md
        - Class 4 Hackathon: module-1/class-4.md
    - 'Module Two: Styling & Routing': 
      - 'Pre-Class 5 Lessons': 
        - Component Styling with Material-UI: module-2/componentStyling.md
        - Class 5 Music App 1/2: module-2/class-5.md
      - 'Pre-Class 6 Lessons':
        - Class Component Lifecycle: module-2/componentLifeCycle.md
        - Class 6 Music App 2/2: module-2/class-6.md
      - 'Pre-Class 7 Lessons':
        - React Router Intro: module-2/reactRouter.md
        - Router Link: module-2/reactRouter-link.md
        - Implement React Router: module-2/implement-ReactRouter.md
        - Class 7: module-2/class-7.md
      - 'Pre-Class 8 Lessons':
        - Protected Routes: module-2/protectedRoutes-intro.md
        - Class 8 Login: module-2/class-8.md
    - 'Module Three: App State': 
      - 'Pre-Class 9 Lessons':
        - Redux Intro: module-3/redux-mapStateToProps.md
        - Redux Setup: module-3/redux-theSetup.md
        - Redux Connect: module-3/redux-connect.md
        - Class 9 Redux MSTP: module-3/class-9.md
      - 'Pre-Class 10 Lessons':
        - Redux Actions: module-3/redux-actions.md  
        - Redux Reducers: module-3/redux-reducers.md  
        - Redux MDTP: module-3/redux-mdtp.md  
        - Redux Using Actions: module-3/redux-usingActions.md  
        - Class 10 Redux MDTP: module-3/class-10.md
      - 'Pre-Class 11 Lessons': 
        - Redux-Thunk: module-3/redux-thunk.md
        - Class 11 Redux-Thunk: module-3/class-11.md
      - 'Pre-Class 12 Lessons': 
        - React Hooks: module-3/reactHooks-intro.md
        - Capstone App pt.1: module-3/capstoneApp-planning-pt1.md
        - Class 12: module-3/class-12.md
      # https://studio.zollege.com/course/course-v1:ACA+JS411+09282020_JS411_C6?show=block-v1%3AACA%2BJS411%2B09282020_JS411_C6%2Btype%40chapter%2Bblock%404de0fa153217497aa24aea294018758d
    - 'Module Four: App Design':
      - 'Pre-Class 13 Lessons':
        - Folder Structure: module-4/folderStructure.md
        - Capstone App pt.2: module-4/capstoneApp-planning-pt2.md
        - Class 13: module-4/class-13.md
      - 'Pre-Class 14 Lessons':
        - NPM Build: module-4/npmBuild-intro.md
        - Capstone App pt.3: module-4/capstoneApp-planning-pt3.md
        - Class 14 Sm. Biz App: module-4/class-14.md
        - Checkpoint Two: module-4/checkpointTwo-smallBizApp.md
      - 'Pre-Class 15 Lessons': 
        - Debugging: module-4/debugging-intro.md
        - Capstone App pt.4: module-4/capstoneApp-planning-pt4.md
        - Class 15: module-4/class-15.md
      - 'Pre-Class 16 Lessons':
        - MVP Shop: module-4/mvpShopInfo.md
        - Deployment: module-4/deployment.md
        - Capstone App pt.5: module-4/capstoneApp-planning-pt5.md
        - Checkpoint Three: module-4/capstoneApp-checkpoint-3.md
        - Class 16: module-4/class-16.md

      # https://studio.zollege.com/course/course-v1:ACA+JS411+09282020_JS411_C6?show=block-v1%3AACA%2BJS411%2B09282020_JS411_C6%2Btype%40chapter%2Bblock%40571217217d8a4fd7a17b286aa707411e
    - Report A Bug: additionalResources/reportABug.md
    - 'Additional Resources':
      - Interview Training: additionalResources/interviewChallenges.md
      - Student Presentations: additionalResources/studentPresentations.md
      - Develop Series Collection: additionalResources/developSeries.md
      - 'Questions for Discussion Collections':
        - Day 1 QFD: additionalResources/questionsForDiscussion/qfd-class-1.md
        - Day 2 QFD: additionalResources/questionsForDiscussion/qfd-class-2.md
        - Day 3 QFD: additionalResources/questionsForDiscussion/qfd-class-3.md
        - Day 4 QFD: additionalResources/questionsForDiscussion/qfd-class-4.md
        - Day 5 QFD: additionalResources/questionsForDiscussion/qfd-class-5.md
        - Day 6 QFD: additionalResources/questionsForDiscussion/qfd-class-6.md
        - Day 7 QFD: additionalResources/questionsForDiscussion/qfd-class-7.md
        - Day 8 QFD: additionalResources/questionsForDiscussion/qfd-class-8.md
        - Day 9 QFD: additionalResources/questionsForDiscussion/qfd-class-9.md
        - Day 10 QFD: additionalResources/questionsForDiscussion/qfd-class-10.md
        - Day 11 QFD: additionalResources/questionsForDiscussion/qfd-class-11.md
        - Day 12 QFD: additionalResources/questionsForDiscussion/qfd-class-12.md
        - Day 13 QFD: additionalResources/questionsForDiscussion/qfd-class-13.md
        - Day 14 QFD: additionalResources/questionsForDiscussion/qfd-class-14.md
        - Day 15 QFD: additionalResources/questionsForDiscussion/qfd-class-15.md
        - Day 16 QFD: additionalResources/questionsForDiscussion/qfd-class-16.md
      - Blog Prompts: additionalResources/blogPrompts.md
      - Keyboard Shortcuts: additionalResources/keyboardShortcuts.md
      - Git & CLI Commands: additionalResources/gitCommands.md
      - Learn Your CLI: additionalResources/learnYourCLI.md
      - Graduation Prerequisites: additionalResources/graduationPrerequisites.md
      - Presentation Qualifications: additionalResources/presentationsQualifications.md
      # - 'Bonus Materials':
      # cp workspace/resources/templateFile.md docs/module-
      # cp workspace/resources/classOutlineTemplate.md docs/module-


# defines the styles, usually just a single name but `custom_dir` overrides this behavior
theme:
  name: material
  # was null
  palette:
    scheme: slate
    primary: black
    accent: pink
    # Defines the logo in the top-left, file must be in the /doc directory
  logo: CE_WhiteBlue_Icon.png
  
  # ? Not rendering as expected??
  extra:
    copyright: Copyright &copy; 2013 - 2021 Austin Coding Academy
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/AustinCodingAcademy
      - icon: fontawesome/brands/medium
        link: https://medium.com/@austincoding
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/school/austincodingacademy/
      - icon: fontawesome/brands/instagram
        link: https://www.instagram.com/austincodingacademy
      - icon: fontawesome/brands/twitter
        link: https://twitter.com/austincoding
      - icon: fontawesome/brands/facebook
        link: https://www.facebook.com/AustinCodingAcademy/


  
  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      clickable_checkbox: true
  - def_list
  - pymdownx.tabbed


 

# Can add icons throughout the ebook https://materialdesignicons.com/
#  - pymdownx.inlinehilite
  # - pymdownx.keys